[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5.0", features = ["fs"] }
serde_json = "1.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
thiserror = "2.0.17"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
async-trait = "0.1.89"
validator = { version = "0.16.1", features = ["derive"] }
axum-extra = { version = "0.9", features = ["cookie"] }
jsonwebtoken = { version = "10.1.0", features = ["rust_crypto"] }
chrono = "0.4.42"
lazy_static = "1.5.0"
dotenvy = "0.15.7"
rand = "0.8.5"
sqlx = { version = "0.8.6", features = [
  "runtime-tokio-rustls",
  "postgres",
  "migrate",
  "macros",
] }
argon2 = { version = "0.5.3", features = ["std"] }
redis = { version = "0.32.7", features = ["tokio-comp"] }

[dev-dependencies]
fake = "=2.3.0"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "cookies",
] }

[features]
default = []
test-trace = []
